### ISSUE TITLE
Should Rubocop enforce omitting parentheses in method calls?

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#2716]
Our libraries consistently use a "no parens" style, but this isn't currently enforced by Rubocop. The following configuration will require it with the exception of multiline calls:

```yaml
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true
```

See [Style/MethodCallWithArgsParentheses](https://github.com/rubocop-hq/rubocop/blob/master/manual/cops_style.md#enforcedstyle-omit_parentheses) for details and examples.
