### ISSUE TITLE
Update Bigtable .rubocop.yml

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#4008]
The following configuration from [ruby-style](https://github.com/googleapis/ruby-style/blob/master/google-style.yml#L42-L47) should be manually added to `.rubocop.yml`, and source code updated as needed to comply with this style:

```
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInCamelCaseMethod: true
  AllowParenthesesInChaining: true
```
